### ISSUE TITLE
Zen Context Menu doesn't work on macOS

### ISSUE THREAD

**Issue by stripedgoat** [KiKaraage/ZenMods#13]
I tried to install/uninstall a few times, but it didn't help.

**Comment by KiKaraage** [comment]
Okay can you try this?
![image](https://github.com/user-attachments/assets/f801ef21-9cfe-4d25-b31e-820452f10011)

**Comment by stripedgoat** [comment]
Thank you very much, that worked straight away! Thanks for the mod!
