### ISSUE TITLE
Completely Disable Back-Forward Buttons option

### ISSUE THREAD

**Issue by abdelrahman-ay** [KiKaraage/ZenMods#2]
can you add the the option do disable back-forward buttons completely ? i made this code and you can use it

Preferences.json
'''[
    {
        "property": "toolbar-hide-back-button",
        "label": "Hide the back button completely",
        "type": "checkbox",	
		"disabledOn": []
    },
    {
        "property": "toolbar-hide-forward-button",
        "label": "Hide the forward button completely",
        "type": "checkbox",
		"disabledOn": []
    }
]
'''

chrome.css
'''
      @-moz-document url-prefix("chrome:") {

@media (-moz-bool-pref: "toolbar-hide-back-button") {
 :root:not([customizing]) #back-button{
    display: none !important;
} 
}      
 :root:not([customizing]) #back-button[disabled] {
    display: none !important;
}
@media (-moz-bool-pref: "toolbar-hide-forward-button") {
 :root:not([customizing]) #forward-button{
    display: none !important;
} 
}
 :root:not([customizing]) #forward-button[disabled] {
    display: none !important;
}
}
'''
thank you in advance!

**Comment by abdelrahman-ay** [comment]
here's an updated version with extra options
preferences.json
```
[
{
"property": "toolbar-hide-overflow-menu",
"label": "Hide the overflow menu completely",
"type": "checkbox",
"disabledOn": []
},
{
"property": "toolbar-hide-application-menu",
"label": "Hide the application menu completely",
"type": "checkbox",
"disabledOn": []
},
{
"property": "toolbar-hide-back-button",
"label": "Hide the back button completely",
"type": "checkbox",
"disabledOn": []
},
{
"property": "toolbar-hide-forward-button",
"label": "Hide the forward button completely",
"type": "checkbox",
"disabledOn": []
}
]
```

chrome.css
```
@-moz-document url-prefix("chrome:") {
  @media (-moz-bool-pref: "toolbar-hide-back-button") {
    :root:not([customizing]) #back-button {
      display: none !important;
    }
  }
  :root:not([customizing]) #back-button[disabled] {
    display: none !important;
  }
  @media (-moz-bool-pref: "toolbar-hide-forward-button") {
    :root:not([customizing]) #forward-button {
      display: none !important;
    }
  }
  :root:not([customizing]) #forward-button[disabled] {
    display: none !important;
  }
  @media (-moz-bool-pref: "toolbar-hide-overflow-menu") {
    :root:not([customizing]) #PlacesChevron,
    #nav-bar-overflow-button {
      display: none !important;
    }
  }
  @media (-moz-bool-pref: "toolbar-hide-application-menu") {
    :root:not([customizing]) #PanelUI-button {
      display: none !important;
    }
  }
}

```

**Comment by KiKaraage** [comment]
I get it, but Back and Forward and the application menu are important buttons designed to be persistent on navbar. 
I made this mod to hide it when it's not usable, not to hide it completely
