### ISSUE TITLE
[Context Menu] Save Image As hidden when option to hide 'Email, Desktop Background, Info' enabled

### ISSUE THREAD

**Issue by sjclayton** [KiKaraage/ZenMods#3]
Hey!!

Love the idea of your mod, thanks for submitting it to the mod store!! 🎉😃

I just wanted to point out that the CSS for the option `Hide “Email Image”, “Set Image as Desktop Background”, and “View Image Info” options` hides the `Save Image As...` context item, which is not included in the description of the option, and also is a very useful item to have access to (people probably wouldn't choose to hide it).

The CSS id `#context-saveimage` should actually be `#context-sendimage`, this successfully removes the `E-mail Image` context item, while retaining `Save Image As...`

Keep up the awesome work!

**Comment by KiKaraage** [comment]
Ah daamn, sorry! I will update it next week 🙏
