### ISSUE TITLE
Zen Context Menu - Road to Update 01

### ISSUE THREAD

**Issue by KiKaraage** [KiKaraage/ZenMods#4]
After the mod is published, [I posted in Reddit](https://www.reddit.com/r/zen_browser/comments/1fy1abh/new_mod_i_made_zen_context_menu_and_the_process/) and people seems to appreciate it. Thank you for your support! So here I'm going to update the mod...

### Ongoing Issues

- [x] #3: "Save Images" is hidden when the mod should be hiding "Email Image" instead

### Things I might hide next... (and its positioning on the Mod settings)

- [x] **Hide all separators** - definitely will be on top
- [x] **Hide all icons** - definitely will be on top
- [x] **New Tab** on tabs context menu (Suggestion by Z3R0 on Discord) - probably higher on the list
- [x] **Move Tab** on tabs context menu (Suggestion by Z3R0 on Discord) - probably higher on the list
- [x] **Mute Tab** on tabs context menu - most likely below Bookmark Tab/Link. I bet this would be useful because mute button is already available on the tab itself
- [x] **Close Duplicate Tab** on tabs context menu - most likely in the middle, this is pretty trivial
- [x] **Duplicate Tab** on tabs context menu - most likely in the middle, this is pretty trivial
- [x] #5

### Future Roadmap

_**Give ability to reordering Custom Menu** (Suggestion by jang on Discord)_
This is totally possible by giving attributes like `order: -1;`, but i feel like it would be effective with GUI method, instead of checkbox/dropdown method Zen Mods is capable currently. Something more suitable as a default Zen feature, but I get why it won't happen soon - this is already in Vivaldi customization level lol

Give me your feedback! I will work on the update once I have free time.
Also, should be v1.1 or v2? I'm confused on this hahaha

**Comment by benstone326** [comment]
Could you please add options in the context menu for video player? I have a shitload of menu that I don't / won't use.
![image](https://github.com/user-attachments/assets/08684857-1eb1-409b-97aa-7b311bcaf4f4)

**Comment by KiKaraage** [comment]
@benstone326 Aaaah yeah! I will work on video options for v1.2.

Though one thing for sure: You can't hide things like "Bookmark Link", "Split link in a new tab", or "Add to Web Panels" specifically for the video context menu - it would also be hidden from the usual context menu for link.

Also yes, I will keep Loop, Show Controls, PiP option and Take Snapshots for video context menu 👍

**Comment by KiKaraage** [comment]
Oh yeah, you can just hide them now with checking the preferences in Mod settings.
