### ISSUE TITLE
Zen Context Menu: Hiding save image option 

### ISSUE THREAD

**Issue by bridgebucket** [KiKaraage/ZenMods#7]
In preferences, the option to "Hide 'Email Image', 'Set Image as Desktop Background', and 'View Image Info'" also hides the 'Save Image As' option, which arguably is more used and is more important than emailing an image, which is what I really want to hide.

**Comment by KiKaraage** [comment]
Yes! I already fixed it on the code itself (this repo), but it would take some time before I push the update to the theme store repo since I still want to add more menu options to hide 😄

**Comment by bridgebucket** [comment]
Looking forward to the update!
