### ISSUE TITLE
Zen Context Menu: Hide `Move Tab` and `Close Tab`

### ISSUE THREAD

**Issue by Wemmy0** [KiKaraage/ZenMods#8]
Add an option to remove the pretty redundant context menu tab actions to re-arrange & close tabs

**Comment by KiKaraage** [comment]
How about making "Close Tab", "Close Duplicate Tabs" and "Close Multiple Tabs" as one config to hide altogether?

**Comment by Wemmy0** [comment]
Yeah that would be great

**Comment by Wemmy0** [comment]
Possibly `Reopen Closed tab` too

**Comment by Wemmy0** [comment]
https://github.com/KiKaraage/ZenMods/pull/10

**Comment by KiKaraage** [comment]
I think `Reopen Closed Tab` is an important feature tho, I'd rather (1) keep RCT not hidden, provide no option to hide it; or (2) have it as a separate option.

**Comment by Wemmy0** [comment]
Another option makes sense because of Control+Shift+T

**Comment by KiKaraage** [comment]
v1.1.4 update already pushed to Mods Store for Move Tab and Close Tab options!
